### ISSUE TITLE
Loot sheet not showing in V3.3.82 using Foundry 8 or 9

### ISSUE THREAD

**Issue by Majea** [jopeek/fvtt-loot-sheet-npc-5e#217] opened 2021-12-23 16:53 UTC
**Describe the bug**
After the update to v 3.3.82, all loot actors open with the default character sheet (tested with Dnd 5e). When we switch the sheet to the loot sheet, the actor doesn't open anymore. We have the following stack trace in the Console: 

foundry.js:316 TypeError: Cannot read properties of undefined (reading 'description')
[Detected 1 package: lootsheetnpc5e]
    at LootSheetNPC5e._prepareGMSettings (LootsheetNPC5e.js:807)
    at LootSheetNPC5e.getData (LootsheetNPC5e.js:68)
    at async LootSheetNPC5e._render (foundry.js:3031)
    at async LootSheetNPC5e._render (foundry.js:3733)

The stack above applies to foundry V9 but the same behaviour is observed on V8. 

**To Reproduce**
1. Open the sheet of an actor set up for a dnd5e.LootSheetNPC5e
2. The sheet opens on the default sheet instead of the loot sheet
3. Click on Sheet on the character sheet
4. Change this sheet to dnd5e.LootSheetNPC5e
5. Save the sheet configuration
6. The sheet doesn't switch to the new layout and this Actor can't be opened anymore

**Expected behavior**
I'm expecting the loot NPC sheet to apply to that actor and appear on the screen.

**Desktop (please complete the following information):**
 - Win 11
 - Foundry built-in (electron) and Chrome  96.0.4664.110 64 bits
 - plugin version: 3.3.82
 - foundry version: 9.238

**Comment by jopeek** [comment] 2021-12-23 17:06
Confirmed. Looks related to permission changes @DanielBoettner

**Comment by jopeek** [comment] 2021-12-23 17:27
hot fix 3.3.83 should get you going again @Majea

**Comment by montycbh** [comment] 2021-12-23 18:29
I am seeing this same issue with the Node.js version. If I roll back the data to a previous compendium version it works. When foundry updates the compendium data I get the basic character sheet, changing it to loot sheet closes the window. It will open again but it draws seemingly random data from my library including an image I uploaded for a PC profile image.
I am running 3.3.82
<img width="594" alt="Screen Shot 2021-12-23 at 12 27 48 PM" src="https://user-images.githubusercontent.com/68304813/147279112-c70711e6-c08d-48cb-abaf-71daa4c9a132.png">
.

**Comment by Majea** [comment] 2021-12-23 18:30
Alright. That was fast. Thanks for that!
So, sheets are back indeed. They are all switched back to the default one and I have to manually switch them to loot sheets again, but that's ok. It's manageable. 

Thanks for the quick response!

**Comment by montycbh** [comment] 2021-12-23 18:40
I upgraded to 3.3.83 and I am seeing the same issue. Should I create a new issue

**Comment by jopeek** [comment] 2021-12-23 18:46
> I upgraded to 3.3.83 and I am seeing the same issue. Should I create a new issue

Which same issue?

**Comment by montycbh** [comment] 2021-12-23 18:53
> Which same issue?

In my previous post I mentioned I was seeing similar behavior with my Node.Js server running this module. I thought maybe they were the same root cause but 3.3.83 doesn't fix it.

I upgraded to foundry version: 9.238.
first time foundry loaded into 9.x the loot sheet (merchants) were working as expected. The next time I launched Foundry said I needed to update the codecs. I did that. All merchants were set back to regular character sheets. Switching them to Loot Sheets resulted in the window closing. Re-opening it gives me this in the window
<img width="595" alt="Screen Shot 2021-12-23 at 12 52 12 PM" src="https://user-images.githubusercontent.com/68304813/147281297-e70dd35b-3fdc-464a-8817-7576c58b6a79.png">


If I reload my user data folder from backup, the sheets are working again however having Foundry updates the codecs to 9.x compatible causes the issue.

**Comment by germandrewboat** [comment] 2021-12-23 18:57
Monty, this looks like it is the exact same issue I'm having; but I wanna confirm. If you resize that saleswoman window all the way to the right do you see the option for Merchant/Loot?

**Comment by jopeek** [comment] 2021-12-23 18:59
Just to reiterate, lootsheet is not yet compatible with v9 nor has it been tested with v9. The hot fix for 3.3.83 is for v8 only and should return functionality in v8. V9 support is not going to happen till the new year most likely.

**Comment by montycbh** [comment] 2021-12-23 19:06
> Monty, this looks like it is the exact same issue I'm having; but I wanna confirm. If you resize that saleswoman window all the way to the right do you see the option for Merchant/Loot?

Yes, if I scroll a very long way

**Comment by DanielBoettner** [comment] 2021-12-24 10:17
@jopeek can we close this issue?

**Closed** 2021-12-24 15:05 UTC
Labels: bug
