### ISSUE TITLE
[Not fixed] cannot buy inventory

### ISSUE THREAD

**Issue by iksior** [jopeek/fvtt-loot-sheet-npc-5e#395] opened 2023-03-20 16:08 UTC
**Describe the bug**
CURRENT VERSION 5.5.

 Issue created in version 5.3 retested on 5.4 and 5.5 and it still persist.
Link to previous issue: https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/393#issue-1621709686

After clicking on buy icon from account with observer account nothing is happenning and error is being displayed in console
**To Reproduce**
1. Create new NPC
2. Change sheet to Loot sheet npc 
3. Add observer permission for a player
3. add item from inventory to npc inventory
4. relog to player account
5. click on npc token 
6. after clicking on BUY icon nothing is happening but error is being displayed in console
`Uncaught TypeError: undefined. Cannot read properties of null (reading '_id')
[Detected 1 package: lootsheet-simple]
    at LootSheet5eNPC._buyItem (lootsheet-simple.js:628:30)
    at HTMLAnchorElement.<anonymous> (lootsheet-simple.js:309:47)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)`

**Expected behavior**
Item should be added to player inv

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version Version 110.0.5481.177 (Official Build) (arm64)

**Additional context**

**Comment by jopeek** [comment] 2023-03-20 16:12
I’ll have a look but can you try this:

Instead of logging out the GM, open a new browser in private mode and log in as the player. Then try to purchase while the GM is logged in still and on the same scene as the player and the lootsheet token.

Thanks

**Comment by iksior** [comment] 2023-03-20 16:13
on it

**Comment by iksior** [comment] 2023-03-20 16:20
Still the same problem. Is there any way that I can share a yt link in more... Private way with the bug?

**Comment by jopeek** [comment] 2023-03-20 16:24
I’ll try to reproduce it tonight and let you know if i can’t. I’ve got the line number so should be easy. What item was it?

**Comment by iksior** [comment] 2023-03-20 16:25
Sent to your email addr jop..k@..... 
In fact it doesn't matter which item. I have the same situation for any item.

**Comment by jopeek** [comment] 2023-03-20 16:27
Ok thanks!

**Comment by jopeek** [comment] 2023-03-24 02:13
The problem is that your player is not assigned to a character, so the sheet has nowhere to send the purchased item. There was supposed to be a proper error message for that but it was not working. That has been fixed in 5.0.6, but you will still need to assign a character to the player in order to purchase or loot.

**Closed as completed by jopeek** 2023-03-24 02:13 UTC
