### ISSUE TITLE
Scroll Icons not being applied to spells manually dragged on to loot sheet

### ISSUE THREAD

**Issue by KevS75** [jopeek/fvtt-loot-sheet-npc-5e#55] opened 2020-08-10 01:11 UTC
Following the DnD5e system change that introduced native handling for spell conversion to scrolls, the loot sheet setting that overrides the spell's native icon is not being applied to spells manually dragged on to the loot sheet.
Spells added manually to the loot sheet and converted to scrolls should obey the loot sheet setting regardless of the method used to add them.
Scrolls added via loot tables (better loot tables) are having their icon updated.

**Comment by pdf** [comment] 2020-08-10 10:53
Dupe of #54?

**Comment by KevS75** [comment] 2020-08-10 10:56
Related but different. Wasn't sure if they should go in the same ticket -
feel free to consolidate if that works best.

**Closed** 2021-03-31 17:05 UTC
Labels: wontfix
